/**
 * Vendored, verbatim curated emoji dataset — ported directly from the
 * desktop client per Phase 4 PRD P4.7 ("no reason to re-curate").
 * Source: reson8/apps/client/src/renderer/renderer.ts (EMOJI_DATA block)
 * Source repo version: 1.4.1
 * Source commit: da9419a478aecf2f0d6f35336a1e8bec1081fbee
 * Copied: 2026-08-16
 *
 * 552 entries across the 9 desktop-defined categories. No content changes
 * beyond adding `export` to each declaration — see CLAUDE.md's vendored-
 * protocol-types convention for the re-sync discipline this follows.
 */

export interface EmojiEntry {
    emoji: string;
    name: string;
    keywords: string[];
    category: string;
}

export const EMOJI_CATEGORIES = [
    "Smileys & Emotion",
    "People & Body",
    "Animals & Nature",
    "Food & Drink",
    "Activities",
    "Travel & Places",
    "Objects",
    "Symbols",
    "Flags",
] as const;

export const EMOJI_CATEGORY_ICONS: Record<string, string> = {
    "Smileys & Emotion": "😀",
    "People & Body": "👋",
    "Animals & Nature": "🐻",
    "Food & Drink": "🍕",
    "Activities": "⚽",
    "Travel & Places": "✈️",
    "Objects": "💡",
    "Symbols": "❤️",
    "Flags": "🏁",
};

export const EMOJI_DATA: EmojiEntry[] = [
    // ── Smileys & Emotion ──
    { emoji: "😀", name: "grinning face", keywords: ["happy", "smile", "grin"], category: "Smileys & Emotion" },
    { emoji: "😃", name: "grinning face with big eyes", keywords: ["happy", "smile", "joy"], category: "Smileys & Emotion" },
    { emoji: "😄", name: "grinning face with smiling eyes", keywords: ["happy", "smile", "joy"], category: "Smileys & Emotion" },
    { emoji: "😁", name: "beaming face", keywords: ["happy", "grin", "teeth"], category: "Smileys & Emotion" },
    { emoji: "😆", name: "grinning squinting face", keywords: ["laugh", "happy", "lol"], category: "Smileys & Emotion" },
    { emoji: "😅", name: "grinning face with sweat", keywords: ["nervous", "laugh", "hot"], category: "Smileys & Emotion" },
    { emoji: "🤣", name: "rolling on the floor laughing", keywords: ["laugh", "lol", "funny", "rofl"], category: "Smileys & Emotion" },
    { emoji: "😂", name: "face with tears of joy", keywords: ["laugh", "cry", "funny", "lol"], category: "Smileys & Emotion" },
    { emoji: "🙂", name: "slightly smiling face", keywords: ["smile", "ok"], category: "Smileys & Emotion" },
    { emoji: "😊", name: "smiling face with smiling eyes", keywords: ["happy", "blush", "smile"], category: "Smileys & Emotion" },
    { emoji: "😇", name: "smiling face with halo", keywords: ["angel", "innocent", "blessed"], category: "Smileys & Emotion" },
    { emoji: "🥰", name: "smiling face with hearts", keywords: ["love", "adore", "crush"], category: "Smileys & Emotion" },
    { emoji: "😍", name: "heart eyes", keywords: ["love", "crush", "beautiful"], category: "Smileys & Emotion" },
    { emoji: "🤩", name: "star struck", keywords: ["excited", "wow", "star"], category: "Smileys & Emotion" },
    { emoji: "😘", name: "face blowing a kiss", keywords: ["love", "kiss", "flirt"], category: "Smileys & Emotion" },
    { emoji: "😗", name: "kissing face", keywords: ["kiss"], category: "Smileys & Emotion" },
    { emoji: "😚", name: "kissing face closed eyes", keywords: ["kiss", "love"], category: "Smileys & Emotion" },
    { emoji: "😋", name: "face savoring food", keywords: ["yummy", "delicious", "tongue"], category: "Smileys & Emotion" },
    { emoji: "😛", name: "face with tongue", keywords: ["tongue", "playful"], category: "Smileys & Emotion" },
    { emoji: "😜", name: "winking face with tongue", keywords: ["tongue", "wink", "playful"], category: "Smileys & Emotion" },
    { emoji: "🤪", name: "zany face", keywords: ["crazy", "wild", "goofy"], category: "Smileys & Emotion" },
    { emoji: "😝", name: "squinting face with tongue", keywords: ["tongue", "playful", "prank"], category: "Smileys & Emotion" },
    { emoji: "🤑", name: "money mouth face", keywords: ["money", "rich", "dollar"], category: "Smileys & Emotion" },
    { emoji: "🤗", name: "hugging face", keywords: ["hug", "love", "warm"], category: "Smileys & Emotion" },
    { emoji: "🤭", name: "face with hand over mouth", keywords: ["oops", "giggle", "shy"], category: "Smileys & Emotion" },
    { emoji: "🤫", name: "shushing face", keywords: ["quiet", "shh", "secret"], category: "Smileys & Emotion" },
    { emoji: "🤔", name: "thinking face", keywords: ["think", "hmm", "wonder"], category: "Smileys & Emotion" },
    { emoji: "🤐", name: "zipper mouth", keywords: ["quiet", "sealed", "secret"], category: "Smileys & Emotion" },
    { emoji: "😐", name: "neutral face", keywords: ["meh", "blank", "indifferent"], category: "Smileys & Emotion" },
    { emoji: "😑", name: "expressionless face", keywords: ["blank", "meh"], category: "Smileys & Emotion" },
    { emoji: "😶", name: "face without mouth", keywords: ["silent", "speechless"], category: "Smileys & Emotion" },
    { emoji: "😏", name: "smirking face", keywords: ["smirk", "flirt", "sly"], category: "Smileys & Emotion" },
    { emoji: "😒", name: "unamused face", keywords: ["bored", "meh", "unimpressed"], category: "Smileys & Emotion" },
    { emoji: "🙄", name: "face with rolling eyes", keywords: ["eyeroll", "whatever", "annoyed"], category: "Smileys & Emotion" },
    { emoji: "😬", name: "grimacing face", keywords: ["awkward", "nervous", "yikes"], category: "Smileys & Emotion" },
    { emoji: "😮‍💨", name: "face exhaling", keywords: ["sigh", "relief", "tired"], category: "Smileys & Emotion" },
    { emoji: "🤥", name: "lying face", keywords: ["lie", "pinocchio"], category: "Smileys & Emotion" },
    { emoji: "😌", name: "relieved face", keywords: ["calm", "peaceful", "content"], category: "Smileys & Emotion" },
    { emoji: "😔", name: "pensive face", keywords: ["sad", "thoughtful"], category: "Smileys & Emotion" },
    { emoji: "😪", name: "sleepy face", keywords: ["tired", "sleep"], category: "Smileys & Emotion" },
    { emoji: "🤤", name: "drooling face", keywords: ["drool", "yummy", "hungry"], category: "Smileys & Emotion" },
    { emoji: "😴", name: "sleeping face", keywords: ["sleep", "zzz", "tired"], category: "Smileys & Emotion" },
    { emoji: "😷", name: "face with medical mask", keywords: ["sick", "mask", "covid"], category: "Smileys & Emotion" },
    { emoji: "🤒", name: "face with thermometer", keywords: ["sick", "fever", "ill"], category: "Smileys & Emotion" },
    { emoji: "🤕", name: "face with bandage", keywords: ["hurt", "injured"], category: "Smileys & Emotion" },
    { emoji: "🤢", name: "nauseated face", keywords: ["sick", "nausea", "green"], category: "Smileys & Emotion" },
    { emoji: "🤮", name: "vomiting face", keywords: ["sick", "puke", "barf"], category: "Smileys & Emotion" },
    { emoji: "🥵", name: "hot face", keywords: ["hot", "sweat", "heat"], category: "Smileys & Emotion" },
    { emoji: "🥶", name: "cold face", keywords: ["cold", "freeze", "ice"], category: "Smileys & Emotion" },
    { emoji: "🥴", name: "woozy face", keywords: ["dizzy", "drunk", "tipsy"], category: "Smileys & Emotion" },
    { emoji: "😵", name: "face with crossed-out eyes", keywords: ["dizzy", "dead", "knocked out"], category: "Smileys & Emotion" },
    { emoji: "🤯", name: "exploding head", keywords: ["mind blown", "shock", "wow"], category: "Smileys & Emotion" },
    { emoji: "🥳", name: "partying face", keywords: ["party", "celebrate", "birthday"], category: "Smileys & Emotion" },
    { emoji: "🥸", name: "disguised face", keywords: ["disguise", "incognito"], category: "Smileys & Emotion" },
    { emoji: "😎", name: "smiling face with sunglasses", keywords: ["cool", "sunglasses", "chill"], category: "Smileys & Emotion" },
    { emoji: "🤓", name: "nerd face", keywords: ["nerd", "geek", "glasses"], category: "Smileys & Emotion" },
    { emoji: "🧐", name: "face with monocle", keywords: ["inspect", "curious", "classy"], category: "Smileys & Emotion" },
    { emoji: "😕", name: "confused face", keywords: ["confused", "puzzled"], category: "Smileys & Emotion" },
    { emoji: "😟", name: "worried face", keywords: ["worried", "nervous", "concern"], category: "Smileys & Emotion" },
    { emoji: "🙁", name: "slightly frowning face", keywords: ["sad", "disappointed"], category: "Smileys & Emotion" },
    { emoji: "😮", name: "face with open mouth", keywords: ["surprise", "shock", "wow"], category: "Smileys & Emotion" },
    { emoji: "😯", name: "hushed face", keywords: ["surprised", "shocked"], category: "Smileys & Emotion" },
    { emoji: "😲", name: "astonished face", keywords: ["shocked", "amazed", "wow"], category: "Smileys & Emotion" },
    { emoji: "😳", name: "flushed face", keywords: ["embarrassed", "blush", "shy"], category: "Smileys & Emotion" },
    { emoji: "🥺", name: "pleading face", keywords: ["please", "puppy eyes", "beg"], category: "Smileys & Emotion" },
    { emoji: "😦", name: "frowning face with open mouth", keywords: ["sad", "surprise"], category: "Smileys & Emotion" },
    { emoji: "😧", name: "anguished face", keywords: ["anguish", "pain", "shocked"], category: "Smileys & Emotion" },
    { emoji: "😨", name: "fearful face", keywords: ["scared", "fear", "shock"], category: "Smileys & Emotion" },
    { emoji: "😰", name: "anxious face with sweat", keywords: ["anxious", "nervous", "sweat"], category: "Smileys & Emotion" },
    { emoji: "😥", name: "sad but relieved face", keywords: ["sad", "relief", "phew"], category: "Smileys & Emotion" },
    { emoji: "😢", name: "crying face", keywords: ["cry", "sad", "tear"], category: "Smileys & Emotion" },
    { emoji: "😭", name: "loudly crying face", keywords: ["cry", "sob", "sad", "bawl"], category: "Smileys & Emotion" },
    { emoji: "😱", name: "face screaming in fear", keywords: ["scream", "horror", "scared"], category: "Smileys & Emotion" },
    { emoji: "😖", name: "confounded face", keywords: ["frustrated", "confused"], category: "Smileys & Emotion" },
    { emoji: "😣", name: "persevering face", keywords: ["struggle", "frustrated"], category: "Smileys & Emotion" },
    { emoji: "😞", name: "disappointed face", keywords: ["sad", "disappointed"], category: "Smileys & Emotion" },
    { emoji: "😓", name: "downcast face with sweat", keywords: ["sad", "tired", "sweat"], category: "Smileys & Emotion" },
    { emoji: "😩", name: "weary face", keywords: ["tired", "exhausted", "fed up"], category: "Smileys & Emotion" },
    { emoji: "😫", name: "tired face", keywords: ["exhausted", "frustrated"], category: "Smileys & Emotion" },
    { emoji: "🥱", name: "yawning face", keywords: ["yawn", "tired", "bored"], category: "Smileys & Emotion" },
    { emoji: "😤", name: "face with steam from nose", keywords: ["angry", "frustrated", "triumph"], category: "Smileys & Emotion" },
    { emoji: "😡", name: "pouting face", keywords: ["angry", "rage", "mad"], category: "Smileys & Emotion" },
    { emoji: "😠", name: "angry face", keywords: ["angry", "mad", "annoyed"], category: "Smileys & Emotion" },
    { emoji: "🤬", name: "face with symbols on mouth", keywords: ["swear", "curse", "angry"], category: "Smileys & Emotion" },
    { emoji: "💀", name: "skull", keywords: ["dead", "death", "skeleton"], category: "Smileys & Emotion" },
    { emoji: "👻", name: "ghost", keywords: ["halloween", "spooky", "boo"], category: "Smileys & Emotion" },
    { emoji: "👽", name: "alien", keywords: ["ufo", "space", "extraterrestrial"], category: "Smileys & Emotion" },
    { emoji: "🤖", name: "robot", keywords: ["bot", "machine", "android"], category: "Smileys & Emotion" },
    { emoji: "💩", name: "pile of poo", keywords: ["poop", "shit", "crap"], category: "Smileys & Emotion" },
    { emoji: "😈", name: "smiling face with horns", keywords: ["devil", "evil", "naughty"], category: "Smileys & Emotion" },
    { emoji: "👿", name: "angry face with horns", keywords: ["devil", "angry", "evil"], category: "Smileys & Emotion" },
    { emoji: "🤡", name: "clown face", keywords: ["clown", "circus", "funny"], category: "Smileys & Emotion" },
    { emoji: "💋", name: "kiss mark", keywords: ["kiss", "lips", "love"], category: "Smileys & Emotion" },
    { emoji: "💯", name: "hundred points", keywords: ["100", "perfect", "score"], category: "Smileys & Emotion" },
    { emoji: "💥", name: "collision", keywords: ["boom", "explosion", "bang"], category: "Smileys & Emotion" },
    { emoji: "💫", name: "dizzy", keywords: ["star", "sparkle", "dizzy"], category: "Smileys & Emotion" },
    { emoji: "💦", name: "sweat droplets", keywords: ["sweat", "water", "splashing"], category: "Smileys & Emotion" },
    { emoji: "❤️", name: "red heart", keywords: ["love", "heart", "valentine"], category: "Smileys & Emotion" },
    { emoji: "🧡", name: "orange heart", keywords: ["love", "heart"], category: "Smileys & Emotion" },
    { emoji: "💛", name: "yellow heart", keywords: ["love", "heart"], category: "Smileys & Emotion" },
    { emoji: "💚", name: "green heart", keywords: ["love", "heart"], category: "Smileys & Emotion" },
    { emoji: "💙", name: "blue heart", keywords: ["love", "heart"], category: "Smileys & Emotion" },
    { emoji: "💜", name: "purple heart", keywords: ["love", "heart"], category: "Smileys & Emotion" },
    { emoji: "🖤", name: "black heart", keywords: ["love", "heart", "dark"], category: "Smileys & Emotion" },
    { emoji: "🤍", name: "white heart", keywords: ["love", "heart", "pure"], category: "Smileys & Emotion" },
    { emoji: "💔", name: "broken heart", keywords: ["heartbreak", "sad", "love"], category: "Smileys & Emotion" },
    { emoji: "🔥", name: "fire", keywords: ["flame", "hot", "lit", "burn"], category: "Smileys & Emotion" },
    { emoji: "⭐", name: "star", keywords: ["star", "favorite", "gold"], category: "Smileys & Emotion" },
    { emoji: "🌟", name: "glowing star", keywords: ["sparkle", "shine", "star"], category: "Smileys & Emotion" },
    { emoji: "✨", name: "sparkles", keywords: ["sparkle", "shine", "magic", "clean"], category: "Smileys & Emotion" },
    // ── People & Body ──
    { emoji: "👋", name: "waving hand", keywords: ["hello", "bye", "wave", "hi"], category: "People & Body" },
    { emoji: "🤚", name: "raised back of hand", keywords: ["hand", "stop"], category: "People & Body" },
    { emoji: "✋", name: "raised hand", keywords: ["stop", "high five", "hand"], category: "People & Body" },
    { emoji: "🖖", name: "vulcan salute", keywords: ["spock", "star trek"], category: "People & Body" },
    { emoji: "👌", name: "ok hand", keywords: ["ok", "perfect", "nice"], category: "People & Body" },
    { emoji: "🤌", name: "pinched fingers", keywords: ["italian", "chef", "what"], category: "People & Body" },
    { emoji: "✌️", name: "victory hand", keywords: ["peace", "v", "two"], category: "People & Body" },
    { emoji: "🤞", name: "crossed fingers", keywords: ["luck", "hope", "fingers crossed"], category: "People & Body" },
    { emoji: "🤟", name: "love you gesture", keywords: ["love", "ily", "rock"], category: "People & Body" },
    { emoji: "🤘", name: "sign of the horns", keywords: ["rock", "metal", "horns"], category: "People & Body" },
    { emoji: "🤙", name: "call me hand", keywords: ["call", "shaka", "hang loose"], category: "People & Body" },
    { emoji: "👈", name: "backhand index pointing left", keywords: ["left", "point", "direction"], category: "People & Body" },
    { emoji: "👉", name: "backhand index pointing right", keywords: ["right", "point", "direction"], category: "People & Body" },
    { emoji: "👆", name: "backhand index pointing up", keywords: ["up", "point"], category: "People & Body" },
    { emoji: "👇", name: "backhand index pointing down", keywords: ["down", "point"], category: "People & Body" },
    { emoji: "☝️", name: "index pointing up", keywords: ["up", "point", "one"], category: "People & Body" },
    { emoji: "👍", name: "thumbs up", keywords: ["like", "approve", "yes", "good", "+1"], category: "People & Body" },
    { emoji: "👎", name: "thumbs down", keywords: ["dislike", "no", "bad", "-1"], category: "People & Body" },
    { emoji: "✊", name: "raised fist", keywords: ["fist", "power", "punch"], category: "People & Body" },
    { emoji: "👊", name: "oncoming fist", keywords: ["punch", "fist bump"], category: "People & Body" },
    { emoji: "🤛", name: "left-facing fist", keywords: ["fist bump"], category: "People & Body" },
    { emoji: "🤜", name: "right-facing fist", keywords: ["fist bump"], category: "People & Body" },
    { emoji: "👏", name: "clapping hands", keywords: ["clap", "applause", "bravo"], category: "People & Body" },
    { emoji: "🙌", name: "raising hands", keywords: ["celebrate", "hooray", "praise"], category: "People & Body" },
    { emoji: "👐", name: "open hands", keywords: ["hands", "open"], category: "People & Body" },
    { emoji: "🤲", name: "palms up together", keywords: ["prayer", "hands"], category: "People & Body" },
    { emoji: "🤝", name: "handshake", keywords: ["agreement", "deal", "meeting"], category: "People & Body" },
    { emoji: "🙏", name: "folded hands", keywords: ["pray", "please", "thank you", "namaste"], category: "People & Body" },
    { emoji: "💪", name: "flexed biceps", keywords: ["strong", "muscle", "arm", "flex"], category: "People & Body" },
    { emoji: "🦾", name: "mechanical arm", keywords: ["robot", "prosthetic", "strong"], category: "People & Body" },
    { emoji: "👀", name: "eyes", keywords: ["look", "see", "watch", "stare"], category: "People & Body" },
    { emoji: "👁️", name: "eye", keywords: ["look", "see"], category: "People & Body" },
    { emoji: "👅", name: "tongue", keywords: ["lick", "taste"], category: "People & Body" },
    { emoji: "👄", name: "mouth", keywords: ["lips", "kiss"], category: "People & Body" },
    { emoji: "🧠", name: "brain", keywords: ["smart", "think", "mind"], category: "People & Body" },
    { emoji: "🫡", name: "saluting face", keywords: ["salute", "respect", "yes sir"], category: "People & Body" },
    { emoji: "🫠", name: "melting face", keywords: ["melt", "hot", "embarrassed"], category: "People & Body" },
    { emoji: "🫣", name: "face with peeking eye", keywords: ["peek", "shy", "scared"], category: "People & Body" },
    { emoji: "🫶", name: "heart hands", keywords: ["love", "heart", "hands"], category: "People & Body" },
    // ── Animals & Nature ──
    { emoji: "🐶", name: "dog face", keywords: ["dog", "puppy", "pet"], category: "Animals & Nature" },
    { emoji: "🐱", name: "cat face", keywords: ["cat", "kitten", "pet"], category: "Animals & Nature" },
    { emoji: "🐭", name: "mouse face", keywords: ["mouse", "rodent"], category: "Animals & Nature" },
    { emoji: "🐹", name: "hamster", keywords: ["hamster", "pet"], category: "Animals & Nature" },
    { emoji: "🐰", name: "rabbit face", keywords: ["rabbit", "bunny"], category: "Animals & Nature" },
    { emoji: "🦊", name: "fox", keywords: ["fox", "cunning"], category: "Animals & Nature" },
    { emoji: "🐻", name: "bear", keywords: ["bear", "teddy"], category: "Animals & Nature" },
    { emoji: "🐼", name: "panda", keywords: ["panda", "bear"], category: "Animals & Nature" },
    { emoji: "🐨", name: "koala", keywords: ["koala", "australia"], category: "Animals & Nature" },
    { emoji: "🐯", name: "tiger face", keywords: ["tiger", "cat"], category: "Animals & Nature" },
    { emoji: "🦁", name: "lion", keywords: ["lion", "king"], category: "Animals & Nature" },
    { emoji: "🐮", name: "cow face", keywords: ["cow", "moo"], category: "Animals & Nature" },
    { emoji: "🐷", name: "pig face", keywords: ["pig", "oink"], category: "Animals & Nature" },
    { emoji: "🐸", name: "frog", keywords: ["frog", "toad", "kermit"], category: "Animals & Nature" },
    { emoji: "🐵", name: "monkey face", keywords: ["monkey", "ape"], category: "Animals & Nature" },
    { emoji: "🙈", name: "see-no-evil monkey", keywords: ["monkey", "hide", "shy"], category: "Animals & Nature" },
    { emoji: "🙉", name: "hear-no-evil monkey", keywords: ["monkey", "ignore"], category: "Animals & Nature" },
    { emoji: "🙊", name: "speak-no-evil monkey", keywords: ["monkey", "oops", "secret"], category: "Animals & Nature" },
    { emoji: "🐔", name: "chicken", keywords: ["chicken", "bird", "hen"], category: "Animals & Nature" },
    { emoji: "🐧", name: "penguin", keywords: ["penguin", "bird", "cold"], category: "Animals & Nature" },
    { emoji: "🦅", name: "eagle", keywords: ["eagle", "bird", "freedom"], category: "Animals & Nature" },
    { emoji: "🦆", name: "duck", keywords: ["duck", "bird", "quack"], category: "Animals & Nature" },
    { emoji: "🦉", name: "owl", keywords: ["owl", "wise", "night"], category: "Animals & Nature" },
    { emoji: "🐝", name: "honeybee", keywords: ["bee", "honey", "buzz"], category: "Animals & Nature" },
    { emoji: "🐛", name: "bug", keywords: ["bug", "insect"], category: "Animals & Nature" },
    { emoji: "🦋", name: "butterfly", keywords: ["butterfly", "pretty", "nature"], category: "Animals & Nature" },
    { emoji: "🐌", name: "snail", keywords: ["snail", "slow"], category: "Animals & Nature" },
    { emoji: "🐙", name: "octopus", keywords: ["octopus", "sea"], category: "Animals & Nature" },
    { emoji: "🐬", name: "dolphin", keywords: ["dolphin", "sea", "ocean"], category: "Animals & Nature" },
    { emoji: "🐳", name: "spouting whale", keywords: ["whale", "ocean"], category: "Animals & Nature" },
    { emoji: "🦈", name: "shark", keywords: ["shark", "ocean", "danger"], category: "Animals & Nature" },
    { emoji: "🐊", name: "crocodile", keywords: ["crocodile", "alligator"], category: "Animals & Nature" },
    { emoji: "🐍", name: "snake", keywords: ["snake", "reptile"], category: "Animals & Nature" },
    { emoji: "🦖", name: "t-rex", keywords: ["dinosaur", "trex", "jurassic"], category: "Animals & Nature" },
    { emoji: "🦕", name: "sauropod", keywords: ["dinosaur", "brontosaurus"], category: "Animals & Nature" },
    { emoji: "🌲", name: "evergreen tree", keywords: ["tree", "nature", "pine", "forest"], category: "Animals & Nature" },
    { emoji: "🌸", name: "cherry blossom", keywords: ["flower", "spring", "sakura"], category: "Animals & Nature" },
    { emoji: "🌹", name: "rose", keywords: ["flower", "love", "romance"], category: "Animals & Nature" },
    { emoji: "🌻", name: "sunflower", keywords: ["flower", "sun", "nature"], category: "Animals & Nature" },
    { emoji: "🍀", name: "four leaf clover", keywords: ["luck", "clover", "irish"], category: "Animals & Nature" },
    { emoji: "🌈", name: "rainbow", keywords: ["rainbow", "pride", "colorful"], category: "Animals & Nature" },
    // ── Food & Drink ──
    { emoji: "🍎", name: "red apple", keywords: ["apple", "fruit"], category: "Food & Drink" },
    { emoji: "🍊", name: "tangerine", keywords: ["orange", "fruit", "citrus"], category: "Food & Drink" },
    { emoji: "🍋", name: "lemon", keywords: ["lemon", "citrus", "sour"], category: "Food & Drink" },
    { emoji: "🍌", name: "banana", keywords: ["banana", "fruit"], category: "Food & Drink" },
    { emoji: "🍉", name: "watermelon", keywords: ["watermelon", "fruit", "summer"], category: "Food & Drink" },
    { emoji: "🍇", name: "grapes", keywords: ["grapes", "fruit", "wine"], category: "Food & Drink" },
    { emoji: "🍓", name: "strawberry", keywords: ["strawberry", "fruit", "berry"], category: "Food & Drink" },
    { emoji: "🫐", name: "blueberries", keywords: ["blueberry", "fruit", "berry"], category: "Food & Drink" },
    { emoji: "🍑", name: "peach", keywords: ["peach", "fruit", "butt"], category: "Food & Drink" },
    { emoji: "🥑", name: "avocado", keywords: ["avocado", "guacamole"], category: "Food & Drink" },
    { emoji: "🍕", name: "pizza", keywords: ["pizza", "food", "slice"], category: "Food & Drink" },
    { emoji: "🍔", name: "hamburger", keywords: ["burger", "food", "fast food"], category: "Food & Drink" },
    { emoji: "🍟", name: "french fries", keywords: ["fries", "food", "chips"], category: "Food & Drink" },
    { emoji: "🌭", name: "hot dog", keywords: ["hotdog", "food", "sausage"], category: "Food & Drink" },
    { emoji: "🍿", name: "popcorn", keywords: ["popcorn", "movie", "snack"], category: "Food & Drink" },
    { emoji: "🧁", name: "cupcake", keywords: ["cupcake", "dessert", "sweet"], category: "Food & Drink" },
    { emoji: "🍰", name: "shortcake", keywords: ["cake", "dessert", "sweet"], category: "Food & Drink" },
    { emoji: "🎂", name: "birthday cake", keywords: ["cake", "birthday", "party"], category: "Food & Drink" },
    { emoji: "🍩", name: "doughnut", keywords: ["donut", "dessert", "sweet"], category: "Food & Drink" },
    { emoji: "🍪", name: "cookie", keywords: ["cookie", "snack", "sweet"], category: "Food & Drink" },
    { emoji: "🍫", name: "chocolate bar", keywords: ["chocolate", "candy", "sweet"], category: "Food & Drink" },
    { emoji: "🍬", name: "candy", keywords: ["candy", "sweet"], category: "Food & Drink" },
    { emoji: "☕", name: "hot beverage", keywords: ["coffee", "tea", "hot", "drink"], category: "Food & Drink" },
    { emoji: "🍵", name: "teacup", keywords: ["tea", "drink", "green tea"], category: "Food & Drink" },
    { emoji: "🧃", name: "beverage box", keywords: ["juice", "drink", "box"], category: "Food & Drink" },
    { emoji: "🍺", name: "beer mug", keywords: ["beer", "drink", "alcohol"], category: "Food & Drink" },
    { emoji: "🍻", name: "clinking beer mugs", keywords: ["beer", "cheers", "drink"], category: "Food & Drink" },
    { emoji: "🥂", name: "clinking glasses", keywords: ["champagne", "cheers", "toast"], category: "Food & Drink" },
    { emoji: "🍷", name: "wine glass", keywords: ["wine", "drink", "red"], category: "Food & Drink" },
    { emoji: "🥤", name: "cup with straw", keywords: ["soda", "drink", "beverage"], category: "Food & Drink" },
    { emoji: "🧊", name: "ice", keywords: ["ice", "cube", "cold"], category: "Food & Drink" },
    // ── Activities ──
    { emoji: "⚽", name: "soccer ball", keywords: ["soccer", "football", "sport"], category: "Activities" },
    { emoji: "🏀", name: "basketball", keywords: ["basketball", "sport", "nba"], category: "Activities" },
    { emoji: "🏈", name: "american football", keywords: ["football", "sport", "nfl"], category: "Activities" },
    { emoji: "⚾", name: "baseball", keywords: ["baseball", "sport"], category: "Activities" },
    { emoji: "🥎", name: "softball", keywords: ["softball", "sport"], category: "Activities" },
    { emoji: "🎾", name: "tennis", keywords: ["tennis", "sport", "ball"], category: "Activities" },
    { emoji: "🏐", name: "volleyball", keywords: ["volleyball", "sport"], category: "Activities" },
    { emoji: "🎱", name: "pool 8 ball", keywords: ["billiards", "pool", "8ball"], category: "Activities" },
    { emoji: "🏓", name: "ping pong", keywords: ["table tennis", "ping pong"], category: "Activities" },
    { emoji: "🎯", name: "bullseye", keywords: ["target", "dart", "goal"], category: "Activities" },
    { emoji: "🎮", name: "video game", keywords: ["game", "controller", "gaming", "play"], category: "Activities" },
    { emoji: "🕹️", name: "joystick", keywords: ["game", "arcade", "retro"], category: "Activities" },
    { emoji: "🎲", name: "game die", keywords: ["dice", "game", "random", "luck"], category: "Activities" },
    { emoji: "🧩", name: "puzzle piece", keywords: ["puzzle", "jigsaw"], category: "Activities" },
    { emoji: "♟️", name: "chess pawn", keywords: ["chess", "game", "strategy"], category: "Activities" },
    { emoji: "🎭", name: "performing arts", keywords: ["theater", "drama", "masks"], category: "Activities" },
    { emoji: "🎨", name: "artist palette", keywords: ["art", "paint", "draw"], category: "Activities" },
    { emoji: "🎬", name: "clapper board", keywords: ["movie", "film", "cinema"], category: "Activities" },
    { emoji: "🎤", name: "microphone", keywords: ["mic", "karaoke", "sing"], category: "Activities" },
    { emoji: "🎧", name: "headphone", keywords: ["headphones", "music", "listen"], category: "Activities" },
    { emoji: "🎵", name: "musical note", keywords: ["music", "note", "song"], category: "Activities" },
    { emoji: "🎶", name: "musical notes", keywords: ["music", "notes", "song", "melody"], category: "Activities" },
    { emoji: "🎸", name: "guitar", keywords: ["guitar", "music", "rock"], category: "Activities" },
    { emoji: "🎹", name: "musical keyboard", keywords: ["piano", "keyboard", "music"], category: "Activities" },
    { emoji: "🥁", name: "drum", keywords: ["drum", "music", "beat"], category: "Activities" },
    { emoji: "🏆", name: "trophy", keywords: ["trophy", "win", "champion", "award"], category: "Activities" },
    { emoji: "🥇", name: "1st place medal", keywords: ["gold", "medal", "first", "winner"], category: "Activities" },
    { emoji: "🥈", name: "2nd place medal", keywords: ["silver", "medal", "second"], category: "Activities" },
    { emoji: "🥉", name: "3rd place medal", keywords: ["bronze", "medal", "third"], category: "Activities" },
    { emoji: "🎪", name: "circus tent", keywords: ["circus", "tent", "carnival"], category: "Activities" },
    // ── Travel & Places ──
    { emoji: "🚗", name: "automobile", keywords: ["car", "drive", "vehicle"], category: "Travel & Places" },
    { emoji: "🚕", name: "taxi", keywords: ["taxi", "cab", "car"], category: "Travel & Places" },
    { emoji: "🚙", name: "sport utility vehicle", keywords: ["suv", "car"], category: "Travel & Places" },
    { emoji: "🚌", name: "bus", keywords: ["bus", "transport"], category: "Travel & Places" },
    { emoji: "🚎", name: "trolleybus", keywords: ["bus", "trolley"], category: "Travel & Places" },
    { emoji: "🏎️", name: "racing car", keywords: ["race", "car", "fast", "f1"], category: "Travel & Places" },
    { emoji: "🚓", name: "police car", keywords: ["police", "car", "cop"], category: "Travel & Places" },
    { emoji: "🚑", name: "ambulance", keywords: ["ambulance", "emergency", "hospital"], category: "Travel & Places" },
    { emoji: "🚒", name: "fire engine", keywords: ["fire truck", "emergency"], category: "Travel & Places" },
    { emoji: "✈️", name: "airplane", keywords: ["plane", "fly", "travel", "flight"], category: "Travel & Places" },
    { emoji: "🚀", name: "rocket", keywords: ["rocket", "space", "launch", "nasa"], category: "Travel & Places" },
    { emoji: "🛸", name: "flying saucer", keywords: ["ufo", "alien", "spaceship"], category: "Travel & Places" },
    { emoji: "🚁", name: "helicopter", keywords: ["helicopter", "chopper"], category: "Travel & Places" },
    { emoji: "🛳️", name: "passenger ship", keywords: ["ship", "cruise", "boat"], category: "Travel & Places" },
    { emoji: "⛵", name: "sailboat", keywords: ["boat", "sail", "sea"], category: "Travel & Places" },
    { emoji: "🏠", name: "house", keywords: ["house", "home", "building"], category: "Travel & Places" },
    { emoji: "🏢", name: "office building", keywords: ["office", "building", "work"], category: "Travel & Places" },
    { emoji: "🏥", name: "hospital", keywords: ["hospital", "health", "building"], category: "Travel & Places" },
    { emoji: "🏫", name: "school", keywords: ["school", "education", "building"], category: "Travel & Places" },
    { emoji: "⛪", name: "church", keywords: ["church", "religion", "building"], category: "Travel & Places" },
    { emoji: "🗽", name: "statue of liberty", keywords: ["liberty", "new york", "usa"], category: "Travel & Places" },
    { emoji: "🗼", name: "tokyo tower", keywords: ["tokyo", "japan", "tower"], category: "Travel & Places" },
    { emoji: "🌍", name: "globe europe africa", keywords: ["earth", "world", "globe"], category: "Travel & Places" },
    { emoji: "🌎", name: "globe americas", keywords: ["earth", "world", "globe"], category: "Travel & Places" },
    { emoji: "🌏", name: "globe asia australia", keywords: ["earth", "world", "globe"], category: "Travel & Places" },
    { emoji: "🌙", name: "crescent moon", keywords: ["moon", "night", "sleep"], category: "Travel & Places" },
    { emoji: "☀️", name: "sun", keywords: ["sun", "bright", "day", "sunny"], category: "Travel & Places" },
    { emoji: "⛅", name: "sun behind cloud", keywords: ["cloud", "weather", "partly cloudy"], category: "Travel & Places" },
    { emoji: "🌧️", name: "cloud with rain", keywords: ["rain", "weather", "cloud"], category: "Travel & Places" },
    { emoji: "⛈️", name: "cloud with lightning and rain", keywords: ["storm", "thunder", "weather"], category: "Travel & Places" },
    { emoji: "❄️", name: "snowflake", keywords: ["snow", "cold", "winter", "ice"], category: "Travel & Places" },
    // ── Objects ──
    { emoji: "⌚", name: "watch", keywords: ["watch", "time", "clock"], category: "Objects" },
    { emoji: "📱", name: "mobile phone", keywords: ["phone", "mobile", "cell", "iphone"], category: "Objects" },
    { emoji: "💻", name: "laptop", keywords: ["computer", "laptop", "mac", "pc"], category: "Objects" },
    { emoji: "⌨️", name: "keyboard", keywords: ["keyboard", "type", "computer"], category: "Objects" },
    { emoji: "🖥️", name: "desktop computer", keywords: ["computer", "monitor", "desktop"], category: "Objects" },
    { emoji: "🖨️", name: "printer", keywords: ["printer", "print", "paper"], category: "Objects" },
    { emoji: "🖱️", name: "computer mouse", keywords: ["mouse", "click", "computer"], category: "Objects" },
    { emoji: "💾", name: "floppy disk", keywords: ["save", "floppy", "disk", "retro"], category: "Objects" },
    { emoji: "💿", name: "optical disk", keywords: ["cd", "disk", "dvd"], category: "Objects" },
    { emoji: "📷", name: "camera", keywords: ["camera", "photo", "picture"], category: "Objects" },
    { emoji: "📹", name: "video camera", keywords: ["video", "camera", "record"], category: "Objects" },
    { emoji: "🎥", name: "movie camera", keywords: ["movie", "film", "camera"], category: "Objects" },
    { emoji: "📺", name: "television", keywords: ["tv", "television", "screen"], category: "Objects" },
    { emoji: "📻", name: "radio", keywords: ["radio", "music"], category: "Objects" },
    { emoji: "🔔", name: "bell", keywords: ["bell", "notification", "alert"], category: "Objects" },
    { emoji: "🔕", name: "bell with slash", keywords: ["mute", "silent", "no bell"], category: "Objects" },
    { emoji: "📢", name: "loudspeaker", keywords: ["speaker", "announce", "loud"], category: "Objects" },
    { emoji: "💡", name: "light bulb", keywords: ["idea", "bulb", "light"], category: "Objects" },
    { emoji: "🔦", name: "flashlight", keywords: ["flashlight", "torch", "light"], category: "Objects" },
    { emoji: "🔧", name: "wrench", keywords: ["tool", "wrench", "fix"], category: "Objects" },
    { emoji: "🔨", name: "hammer", keywords: ["tool", "hammer", "build"], category: "Objects" },
    { emoji: "⚙️", name: "gear", keywords: ["settings", "gear", "cog"], category: "Objects" },
    { emoji: "🔗", name: "link", keywords: ["link", "chain", "url"], category: "Objects" },
    { emoji: "📎", name: "paperclip", keywords: ["paperclip", "attach", "clip"], category: "Objects" },
    { emoji: "🔒", name: "locked", keywords: ["lock", "security", "private"], category: "Objects" },
    { emoji: "🔓", name: "unlocked", keywords: ["unlock", "open", "security"], category: "Objects" },
    { emoji: "🔑", name: "key", keywords: ["key", "password", "lock"], category: "Objects" },
    { emoji: "📝", name: "memo", keywords: ["note", "write", "memo", "pencil"], category: "Objects" },
    { emoji: "📁", name: "file folder", keywords: ["folder", "file", "directory"], category: "Objects" },
    { emoji: "📂", name: "open file folder", keywords: ["folder", "file", "open"], category: "Objects" },
    { emoji: "📅", name: "calendar", keywords: ["calendar", "date", "schedule"], category: "Objects" },
    { emoji: "📌", name: "pushpin", keywords: ["pin", "location", "pushpin"], category: "Objects" },
    { emoji: "📍", name: "round pushpin", keywords: ["pin", "location"], category: "Objects" },
    { emoji: "✏️", name: "pencil", keywords: ["pencil", "write", "edit"], category: "Objects" },
    { emoji: "🎁", name: "wrapped gift", keywords: ["gift", "present", "birthday"], category: "Objects" },
    { emoji: "🎈", name: "balloon", keywords: ["balloon", "party", "celebration"], category: "Objects" },
    { emoji: "🎉", name: "party popper", keywords: ["party", "celebrate", "tada", "congratulations"], category: "Objects" },
    { emoji: "🎊", name: "confetti ball", keywords: ["confetti", "party", "celebrate"], category: "Objects" },
    // ── Symbols ──
    { emoji: "✅", name: "check mark button", keywords: ["check", "done", "yes", "correct"], category: "Symbols" },
    { emoji: "❌", name: "cross mark", keywords: ["no", "wrong", "delete", "x"], category: "Symbols" },
    { emoji: "❓", name: "question mark", keywords: ["question", "what", "help"], category: "Symbols" },
    { emoji: "❗", name: "exclamation mark", keywords: ["exclamation", "important", "alert"], category: "Symbols" },
    { emoji: "‼️", name: "double exclamation mark", keywords: ["exclamation", "important"], category: "Symbols" },
    { emoji: "⁉️", name: "exclamation question mark", keywords: ["surprise", "what"], category: "Symbols" },
    { emoji: "💤", name: "zzz", keywords: ["sleep", "tired", "zzz"], category: "Symbols" },
    { emoji: "💬", name: "speech balloon", keywords: ["chat", "message", "talk", "speech"], category: "Symbols" },
    { emoji: "💭", name: "thought balloon", keywords: ["think", "thought", "bubble"], category: "Symbols" },
    { emoji: "🔴", name: "red circle", keywords: ["red", "circle", "dot"], category: "Symbols" },
    { emoji: "🟠", name: "orange circle", keywords: ["orange", "circle"], category: "Symbols" },
    { emoji: "🟡", name: "yellow circle", keywords: ["yellow", "circle"], category: "Symbols" },
    { emoji: "🟢", name: "green circle", keywords: ["green", "circle", "online"], category: "Symbols" },
    { emoji: "🔵", name: "blue circle", keywords: ["blue", "circle"], category: "Symbols" },
    { emoji: "🟣", name: "purple circle", keywords: ["purple", "circle"], category: "Symbols" },
    { emoji: "⚫", name: "black circle", keywords: ["black", "circle"], category: "Symbols" },
    { emoji: "⚪", name: "white circle", keywords: ["white", "circle"], category: "Symbols" },
    { emoji: "➕", name: "plus", keywords: ["plus", "add", "math"], category: "Symbols" },
    { emoji: "➖", name: "minus", keywords: ["minus", "subtract", "math"], category: "Symbols" },
    { emoji: "➗", name: "divide", keywords: ["divide", "math"], category: "Symbols" },
    { emoji: "✖️", name: "multiply", keywords: ["multiply", "math", "times"], category: "Symbols" },
    { emoji: "♻️", name: "recycling symbol", keywords: ["recycle", "environment", "green"], category: "Symbols" },
    { emoji: "⚠️", name: "warning", keywords: ["warning", "caution", "alert"], category: "Symbols" },
    { emoji: "🚫", name: "prohibited", keywords: ["no", "forbidden", "ban", "stop"], category: "Symbols" },
    { emoji: "🔞", name: "no one under eighteen", keywords: ["18", "adult", "nsfw"], category: "Symbols" },
    { emoji: "ℹ️", name: "information", keywords: ["info", "information", "help"], category: "Symbols" },
    { emoji: "🆗", name: "ok button", keywords: ["ok", "yes", "agree"], category: "Symbols" },
    { emoji: "🆕", name: "new button", keywords: ["new", "fresh"], category: "Symbols" },
    { emoji: "🆙", name: "up button", keywords: ["up", "level up"], category: "Symbols" },
    { emoji: "🔝", name: "top arrow", keywords: ["top", "up", "first"], category: "Symbols" },
    { emoji: "🏧", name: "atm sign", keywords: ["atm", "money", "bank"], category: "Symbols" },
    { emoji: "♾️", name: "infinity", keywords: ["infinity", "forever", "loop"], category: "Symbols" },
    // ── Flags ──
    { emoji: "🏁", name: "chequered flag", keywords: ["race", "finish", "checkered"], category: "Flags" },
    { emoji: "🚩", name: "triangular flag", keywords: ["flag", "red flag", "warning"], category: "Flags" },
    { emoji: "🎌", name: "crossed flags", keywords: ["flags", "japan", "celebration"], category: "Flags" },
    { emoji: "🏴", name: "black flag", keywords: ["flag", "black", "pirate"], category: "Flags" },
    { emoji: "🏳️", name: "white flag", keywords: ["flag", "white", "surrender", "peace"], category: "Flags" },
    { emoji: "🏳️‍🌈", name: "rainbow flag", keywords: ["pride", "lgbtq", "rainbow", "gay"], category: "Flags" },
    { emoji: "🏴‍☠️", name: "pirate flag", keywords: ["pirate", "skull", "jolly roger"], category: "Flags" },
    { emoji: "🇺🇸", name: "flag united states", keywords: ["usa", "america", "us"], category: "Flags" },
    { emoji: "🇬🇧", name: "flag united kingdom", keywords: ["uk", "britain", "england"], category: "Flags" },
    { emoji: "🇨🇦", name: "flag canada", keywords: ["canada", "maple"], category: "Flags" },
    { emoji: "🇦🇺", name: "flag australia", keywords: ["australia"], category: "Flags" },
    { emoji: "🇩🇪", name: "flag germany", keywords: ["germany", "deutschland"], category: "Flags" },
    { emoji: "🇫🇷", name: "flag france", keywords: ["france", "french"], category: "Flags" },
    { emoji: "🇪🇸", name: "flag spain", keywords: ["spain", "spanish"], category: "Flags" },
    { emoji: "🇮🇹", name: "flag italy", keywords: ["italy", "italian"], category: "Flags" },
    { emoji: "🇧🇷", name: "flag brazil", keywords: ["brazil", "brazilian"], category: "Flags" },
    { emoji: "🇯🇵", name: "flag japan", keywords: ["japan", "japanese"], category: "Flags" },
    { emoji: "🇰🇷", name: "flag south korea", keywords: ["korea", "korean"], category: "Flags" },
    { emoji: "🇮🇳", name: "flag india", keywords: ["india", "indian"], category: "Flags" },
    { emoji: "🇲🇽", name: "flag mexico", keywords: ["mexico", "mexican"], category: "Flags" },
    { emoji: "🇦🇷", name: "flag argentina", keywords: ["argentina"], category: "Flags" },

    // ── Gap-fill: commonly-expected default emoji missing from the set above (PRD 4.9) ──
    // ── Smileys & Emotion ──
    { emoji: "😉", name: "winking face", keywords: ["wink", "flirt"], category: "Smileys & Emotion" },
    { emoji: "🙃", name: "upside-down face", keywords: ["silly", "sarcasm"], category: "Smileys & Emotion" },
    { emoji: "☺️", name: "smiling face", keywords: ["smile", "happy", "relaxed"], category: "Smileys & Emotion" },
    { emoji: "😙", name: "kissing face with smiling eyes", keywords: ["kiss", "affection"], category: "Smileys & Emotion" },
    { emoji: "🤨", name: "face with raised eyebrow", keywords: ["skeptical", "suspicious", "distrust"], category: "Smileys & Emotion" },
    { emoji: "🤧", name: "sneezing face", keywords: ["sick", "sneeze", "gesundheit"], category: "Smileys & Emotion" },
    { emoji: "🤠", name: "cowboy hat face", keywords: ["cowboy", "cowgirl", "hat"], category: "Smileys & Emotion" },
    { emoji: "🥲", name: "smiling face with tear", keywords: ["bittersweet", "proud", "touched"], category: "Smileys & Emotion" },
    { emoji: "🥹", name: "face holding back tears", keywords: ["touched", "proud", "emotional"], category: "Smileys & Emotion" },
    { emoji: "😵‍💫", name: "face with spiral eyes", keywords: ["dizzy", "confused"], category: "Smileys & Emotion" },
    { emoji: "🫥", name: "dotted line face", keywords: ["invisible", "shy", "blend in"], category: "Smileys & Emotion" },

    // ── People & Body ──
    { emoji: "🤦", name: "person facepalming", keywords: ["facepalm", "disbelief"], category: "People & Body" },
    { emoji: "🤷", name: "person shrugging", keywords: ["shrug", "idk", "unknown"], category: "People & Body" },
    { emoji: "💃", name: "woman dancing", keywords: ["dance", "party"], category: "People & Body" },
    { emoji: "🕺", name: "man dancing", keywords: ["dance", "party"], category: "People & Body" },
    { emoji: "🚶", name: "person walking", keywords: ["walk", "pedestrian"], category: "People & Body" },
    { emoji: "🏃", name: "person running", keywords: ["run", "race", "jog"], category: "People & Body" },
    { emoji: "👶", name: "baby", keywords: ["infant", "newborn"], category: "People & Body" },
    { emoji: "🧒", name: "child", keywords: ["kid"], category: "People & Body" },
    { emoji: "👦", name: "boy", keywords: ["child", "kid"], category: "People & Body" },
    { emoji: "👧", name: "girl", keywords: ["child", "kid"], category: "People & Body" },
    { emoji: "👨", name: "man", keywords: ["adult"], category: "People & Body" },
    { emoji: "👩", name: "woman", keywords: ["adult"], category: "People & Body" },
    { emoji: "👴", name: "old man", keywords: ["elder", "senior"], category: "People & Body" },
    { emoji: "👵", name: "old woman", keywords: ["elder", "senior"], category: "People & Body" },
    { emoji: "🙋", name: "person raising hand", keywords: ["question", "volunteer"], category: "People & Body" },
    { emoji: "💁", name: "person tipping hand", keywords: ["information", "sassy"], category: "People & Body" },
    { emoji: "🙇", name: "person bowing", keywords: ["sorry", "respect", "apology"], category: "People & Body" },
    { emoji: "🧑‍💻", name: "technologist", keywords: ["coder", "developer", "programmer"], category: "People & Body" },
    { emoji: "👣", name: "footprints", keywords: ["tracks", "steps"], category: "People & Body" },

    // ── Animals & Nature ──
    { emoji: "🦄", name: "unicorn", keywords: ["mythical", "fantasy"], category: "Animals & Nature" },
    { emoji: "🐺", name: "wolf", keywords: ["animal"], category: "Animals & Nature" },
    { emoji: "🐴", name: "horse face", keywords: ["animal", "pony"], category: "Animals & Nature" },
    { emoji: "🐢", name: "turtle", keywords: ["slow", "animal"], category: "Animals & Nature" },
    { emoji: "🦀", name: "crab", keywords: ["animal", "seafood"], category: "Animals & Nature" },
    { emoji: "🐟", name: "fish", keywords: ["animal", "seafood"], category: "Animals & Nature" },
    { emoji: "🐠", name: "tropical fish", keywords: ["animal", "aquarium"], category: "Animals & Nature" },
    { emoji: "🕷️", name: "spider", keywords: ["bug", "creepy"], category: "Animals & Nature" },
    { emoji: "🦂", name: "scorpion", keywords: ["bug", "zodiac"], category: "Animals & Nature" },
    { emoji: "🦇", name: "bat", keywords: ["animal", "vampire", "night"], category: "Animals & Nature" },
    { emoji: "🐣", name: "hatching chick", keywords: ["bird", "baby", "new"], category: "Animals & Nature" },
    { emoji: "🌴", name: "palm tree", keywords: ["tropical", "beach"], category: "Animals & Nature" },
    { emoji: "🌵", name: "cactus", keywords: ["desert", "plant"], category: "Animals & Nature" },
    { emoji: "🍁", name: "maple leaf", keywords: ["autumn", "fall", "canada"], category: "Animals & Nature" },
    { emoji: "🍂", name: "fallen leaves", keywords: ["autumn", "fall"], category: "Animals & Nature" },
    { emoji: "🌱", name: "seedling", keywords: ["plant", "growth", "new"], category: "Animals & Nature" },
    { emoji: "🌷", name: "tulip", keywords: ["flower", "spring"], category: "Animals & Nature" },
    { emoji: "💐", name: "bouquet", keywords: ["flowers", "gift"], category: "Animals & Nature" },
    { emoji: "🌼", name: "blossom", keywords: ["flower"], category: "Animals & Nature" },

    // ── Food & Drink ──
    { emoji: "🍒", name: "cherries", keywords: ["fruit"], category: "Food & Drink" },
    { emoji: "🍅", name: "tomato", keywords: ["vegetable", "fruit"], category: "Food & Drink" },
    { emoji: "🥕", name: "carrot", keywords: ["vegetable"], category: "Food & Drink" },
    { emoji: "🌽", name: "corn", keywords: ["vegetable"], category: "Food & Drink" },
    { emoji: "🥦", name: "broccoli", keywords: ["vegetable"], category: "Food & Drink" },
    { emoji: "🧀", name: "cheese wedge", keywords: ["dairy"], category: "Food & Drink" },
    { emoji: "🥓", name: "bacon", keywords: ["meat", "breakfast"], category: "Food & Drink" },
    { emoji: "🍞", name: "bread", keywords: ["loaf", "bakery"], category: "Food & Drink" },
    { emoji: "🥐", name: "croissant", keywords: ["bakery", "breakfast"], category: "Food & Drink" },
    { emoji: "🥪", name: "sandwich", keywords: ["lunch"], category: "Food & Drink" },
    { emoji: "🌮", name: "taco", keywords: ["mexican"], category: "Food & Drink" },
    { emoji: "🌯", name: "burrito", keywords: ["mexican", "wrap"], category: "Food & Drink" },
    { emoji: "🍝", name: "spaghetti", keywords: ["pasta", "italian"], category: "Food & Drink" },
    { emoji: "🍜", name: "steaming bowl", keywords: ["ramen", "noodles", "soup"], category: "Food & Drink" },
    { emoji: "🍣", name: "sushi", keywords: ["japanese", "seafood"], category: "Food & Drink" },
    { emoji: "🍦", name: "soft ice cream", keywords: ["dessert", "sweet"], category: "Food & Drink" },
    { emoji: "🍨", name: "ice cream", keywords: ["dessert", "sweet"], category: "Food & Drink" },
    { emoji: "🍭", name: "lollipop", keywords: ["candy", "sweet"], category: "Food & Drink" },
    { emoji: "🍯", name: "honey pot", keywords: ["sweet", "bees"], category: "Food & Drink" },
    { emoji: "🥛", name: "glass of milk", keywords: ["drink", "dairy"], category: "Food & Drink" },
    { emoji: "🍸", name: "cocktail glass", keywords: ["drink", "alcohol"], category: "Food & Drink" },
    { emoji: "🥃", name: "tumbler glass", keywords: ["whisky", "drink", "alcohol"], category: "Food & Drink" },
    { emoji: "🍾", name: "bottle with popping cork", keywords: ["champagne", "celebration"], category: "Food & Drink" },

    // ── Activities ──
    { emoji: "🏸", name: "badminton", keywords: ["sport", "racquet"], category: "Activities" },
    { emoji: "🏒", name: "ice hockey", keywords: ["sport"], category: "Activities" },
    { emoji: "🏏", name: "cricket game", keywords: ["sport"], category: "Activities" },
    { emoji: "🥊", name: "boxing glove", keywords: ["sport", "fight"], category: "Activities" },
    { emoji: "⛳", name: "flag in hole", keywords: ["golf", "sport"], category: "Activities" },
    { emoji: "🎳", name: "bowling", keywords: ["sport", "strike"], category: "Activities" },
    { emoji: "🎣", name: "fishing pole", keywords: ["fish", "hobby"], category: "Activities" },
    { emoji: "🎿", name: "skis", keywords: ["winter", "sport"], category: "Activities" },
    { emoji: "🏂", name: "snowboarder", keywords: ["winter", "sport"], category: "Activities" },
    { emoji: "🏋️", name: "person lifting weights", keywords: ["gym", "workout"], category: "Activities" },
    { emoji: "🚴", name: "person biking", keywords: ["cycling", "sport"], category: "Activities" },
    { emoji: "🎖️", name: "military medal", keywords: ["award", "honor"], category: "Activities" },
    { emoji: "🎫", name: "ticket", keywords: ["event", "admission"], category: "Activities" },

    // ── Travel & Places ──
    { emoji: "🚲", name: "bicycle", keywords: ["bike", "cycling"], category: "Travel & Places" },
    { emoji: "🏍️", name: "motorcycle", keywords: ["bike", "motorbike"], category: "Travel & Places" },
    { emoji: "🚂", name: "locomotive", keywords: ["train"], category: "Travel & Places" },
    { emoji: "🚦", name: "vertical traffic light", keywords: ["stop", "go", "signal"], category: "Travel & Places" },
    { emoji: "⛽", name: "fuel pump", keywords: ["gas", "station"], category: "Travel & Places" },
    { emoji: "🗺️", name: "world map", keywords: ["travel", "geography"], category: "Travel & Places" },
    { emoji: "🧭", name: "compass", keywords: ["navigation", "direction"], category: "Travel & Places" },
    { emoji: "⛰️", name: "mountain", keywords: ["nature", "hike"], category: "Travel & Places" },
    { emoji: "🏖️", name: "beach with umbrella", keywords: ["vacation", "sand"], category: "Travel & Places" },
    { emoji: "🌋", name: "volcano", keywords: ["nature", "eruption"], category: "Travel & Places" },
    { emoji: "🏰", name: "castle", keywords: ["fairytale", "building"], category: "Travel & Places" },
    { emoji: "🎡", name: "ferris wheel", keywords: ["carnival", "fair"], category: "Travel & Places" },
    { emoji: "🎢", name: "roller coaster", keywords: ["amusement", "park"], category: "Travel & Places" },
    { emoji: "🌅", name: "sunrise", keywords: ["morning", "dawn"], category: "Travel & Places" },
    { emoji: "🎆", name: "fireworks", keywords: ["celebration", "night"], category: "Travel & Places" },
    { emoji: "🌊", name: "water wave", keywords: ["ocean", "sea", "surf"], category: "Travel & Places" },
    { emoji: "⚡", name: "high voltage", keywords: ["lightning", "bolt", "electric"], category: "Travel & Places" },
    { emoji: "☔", name: "umbrella with rain drops", keywords: ["rain", "weather"], category: "Travel & Places" },
    { emoji: "⛄", name: "snowman without snow", keywords: ["winter", "cold"], category: "Travel & Places" },
    { emoji: "🌡️", name: "thermometer", keywords: ["temperature", "weather"], category: "Travel & Places" },

    // ── Objects ──
    { emoji: "📚", name: "books", keywords: ["read", "study", "library"], category: "Objects" },
    { emoji: "✂️", name: "scissors", keywords: ["cut", "craft"], category: "Objects" },
    { emoji: "🗑️", name: "wastebasket", keywords: ["trash", "delete"], category: "Objects" },
    { emoji: "🛒", name: "shopping cart", keywords: ["shopping", "store"], category: "Objects" },
    { emoji: "💰", name: "money bag", keywords: ["cash", "rich"], category: "Objects" },
    { emoji: "💵", name: "dollar banknote", keywords: ["money", "cash"], category: "Objects" },
    { emoji: "💳", name: "credit card", keywords: ["payment", "money"], category: "Objects" },
    { emoji: "👑", name: "crown", keywords: ["king", "queen", "royalty"], category: "Objects" },
    { emoji: "💎", name: "gem stone", keywords: ["diamond", "jewel"], category: "Objects" },
    { emoji: "🕶️", name: "sunglasses", keywords: ["cool", "shades"], category: "Objects" },
    { emoji: "👓", name: "glasses", keywords: ["eyewear", "nerd"], category: "Objects" },
    { emoji: "👔", name: "necktie", keywords: ["clothing", "formal"], category: "Objects" },
    { emoji: "👕", name: "t-shirt", keywords: ["clothing", "shirt"], category: "Objects" },
    { emoji: "👗", name: "dress", keywords: ["clothing"], category: "Objects" },
    { emoji: "👟", name: "running shoe", keywords: ["sneaker", "clothing"], category: "Objects" },
    { emoji: "🎩", name: "top hat", keywords: ["formal", "magic"], category: "Objects" },
    { emoji: "🧢", name: "billed cap", keywords: ["hat", "clothing"], category: "Objects" },
    { emoji: "💄", name: "lipstick", keywords: ["makeup", "beauty"], category: "Objects" },
    { emoji: "💍", name: "ring", keywords: ["jewelry", "engagement", "wedding"], category: "Objects" },
    { emoji: "🛏️", name: "bed", keywords: ["sleep", "furniture"], category: "Objects" },
    { emoji: "🪑", name: "chair", keywords: ["furniture", "seat"], category: "Objects" },
    { emoji: "🧸", name: "teddy bear", keywords: ["toy", "cute"], category: "Objects" },
    { emoji: "💊", name: "pill", keywords: ["medicine", "health"], category: "Objects" },
    { emoji: "💉", name: "syringe", keywords: ["medicine", "injection", "vaccine"], category: "Objects" },

    // ── Symbols ──
    { emoji: "💲", name: "heavy dollar sign", keywords: ["money", "currency"], category: "Symbols" },
    { emoji: "#️⃣", name: "keycap hash", keywords: ["hashtag", "number"], category: "Symbols" },
    { emoji: "✔️", name: "check mark", keywords: ["done", "yes", "correct"], category: "Symbols" },
    { emoji: "☑️", name: "check box with check", keywords: ["done", "selected"], category: "Symbols" },
    { emoji: "🔀", name: "shuffle tracks button", keywords: ["random", "music"], category: "Symbols" },
    { emoji: "🔁", name: "repeat button", keywords: ["loop", "again"], category: "Symbols" },
    { emoji: "⏯️", name: "play or pause button", keywords: ["media", "video"], category: "Symbols" },
    { emoji: "⏹️", name: "stop button", keywords: ["media", "video"], category: "Symbols" },
    { emoji: "⬆️", name: "up arrow", keywords: ["direction", "north"], category: "Symbols" },
    { emoji: "⬇️", name: "down arrow", keywords: ["direction", "south"], category: "Symbols" },
    { emoji: "⬅️", name: "left arrow", keywords: ["direction", "back", "west"], category: "Symbols" },
    { emoji: "➡️", name: "right arrow", keywords: ["direction", "next", "east"], category: "Symbols" },
    { emoji: "🔄", name: "counterclockwise arrows button", keywords: ["refresh", "reload", "sync"], category: "Symbols" },
    { emoji: "🔢", name: "input numbers", keywords: ["1234", "digits"], category: "Symbols" },
    { emoji: "💠", name: "diamond with a dot", keywords: ["shape"], category: "Symbols" },
    { emoji: "🔘", name: "radio button", keywords: ["select", "option"], category: "Symbols" },
    { emoji: "⬛", name: "black large square", keywords: ["shape", "square"], category: "Symbols" },
    { emoji: "⬜", name: "white large square", keywords: ["shape", "square"], category: "Symbols" },
    { emoji: "🟥", name: "red square", keywords: ["shape", "color"], category: "Symbols" },
    { emoji: "🟩", name: "green square", keywords: ["shape", "color"], category: "Symbols" },
    { emoji: "🟦", name: "blue square", keywords: ["shape", "color"], category: "Symbols" },
    { emoji: "💞", name: "revolving hearts", keywords: ["love", "affection"], category: "Symbols" },
    { emoji: "💕", name: "two hearts", keywords: ["love", "affection"], category: "Symbols" },
    { emoji: "💓", name: "beating heart", keywords: ["love", "pulse"], category: "Symbols" },
    { emoji: "💗", name: "growing heart", keywords: ["love", "excited"], category: "Symbols" },
    { emoji: "💖", name: "sparkling heart", keywords: ["love", "shiny"], category: "Symbols" },
    { emoji: "💘", name: "heart with arrow", keywords: ["love", "cupid", "crush"], category: "Symbols" },
    { emoji: "❤️‍🔥", name: "heart on fire", keywords: ["love", "passion", "burning"], category: "Symbols" },

    // ── Flags ──
    { emoji: "🇨🇳", name: "flag china", keywords: ["china", "chinese"], category: "Flags" },
    { emoji: "🇷🇺", name: "flag russia", keywords: ["russia", "russian"], category: "Flags" },
    { emoji: "🇵🇹", name: "flag portugal", keywords: ["portugal", "portuguese"], category: "Flags" },
    { emoji: "🇳🇱", name: "flag netherlands", keywords: ["netherlands", "dutch", "holland"], category: "Flags" },
    { emoji: "🇸🇪", name: "flag sweden", keywords: ["sweden", "swedish"], category: "Flags" },
    { emoji: "🇨🇭", name: "flag switzerland", keywords: ["switzerland", "swiss"], category: "Flags" },
    { emoji: "🇵🇱", name: "flag poland", keywords: ["poland", "polish"], category: "Flags" },
    { emoji: "🇹🇷", name: "flag turkey", keywords: ["turkey", "turkish"], category: "Flags" },
    { emoji: "🇿🇦", name: "flag south africa", keywords: ["south africa"], category: "Flags" },
    { emoji: "🇺🇦", name: "flag ukraine", keywords: ["ukraine", "ukrainian"], category: "Flags" },
    { emoji: "🇵🇭", name: "flag philippines", keywords: ["philippines", "filipino"], category: "Flags" },
    { emoji: "🇮🇩", name: "flag indonesia", keywords: ["indonesia", "indonesian"], category: "Flags" },
    { emoji: "🇻🇳", name: "flag vietnam", keywords: ["vietnam", "vietnamese"], category: "Flags" },
    { emoji: "🇹🇭", name: "flag thailand", keywords: ["thailand", "thai"], category: "Flags" },
    { emoji: "🇮🇪", name: "flag ireland", keywords: ["ireland", "irish"], category: "Flags" },
    { emoji: "🇳🇴", name: "flag norway", keywords: ["norway", "norwegian"], category: "Flags" },
    { emoji: "🇩🇰", name: "flag denmark", keywords: ["denmark", "danish"], category: "Flags" },
    { emoji: "🇬🇷", name: "flag greece", keywords: ["greece", "greek"], category: "Flags" },
    { emoji: "🇪🇬", name: "flag egypt", keywords: ["egypt", "egyptian"], category: "Flags" },
    { emoji: "🇳🇬", name: "flag nigeria", keywords: ["nigeria", "nigerian"], category: "Flags" },
    { emoji: "🇮🇱", name: "flag israel", keywords: ["israel", "israeli"], category: "Flags" },
    { emoji: "🇳🇿", name: "flag new zealand", keywords: ["new zealand", "kiwi"], category: "Flags" },
];
